### ISSUE TITLE
can you use it to emulate fax?

### ISSUE THREAD

**Issue by jlemaire36** [tolsen64/InternetModem#2]
i would like to know if it's possible to use it as a virtual fax modem so i could play around with fax softwares, that would be cool

(please note that i cannot execute Linux commands as i'm on windows)

**Comment by tolsen64** [comment]
I don’t think so. Internet Modem connects a serial device to the internet. As far as I know, fax machines don’t have serial ports, only an RJ-11 port.

I asked ChatGPT if the modem in a fax machine used the standard Hayes protocol (which is what Internet Modem uses) and it gave me this:

Fax machine modems do not typically use the Hayes protocol. The Hayes protocol, also known as the AT command set, was a widely used standard for controlling modems in the past. It provided a standardized set of commands that allowed communication between the modem and the computer.
Fax machines, on the other hand, use a different set of protocols specifically designed for fax transmission. The most common fax protocols are ITU-T T.30 and T.38.
ITU-T T.30 is the protocol used for fax communication over traditional telephone lines. It defines the signaling and control procedures for fax transmission, including handshaking, page negotiation, and error correction.
ITU-T T.38 is a protocol used for fax over IP (FoIP) transmission, which allows fax communication over IP networks such as the internet. T.38 encapsulates the fax data in real-time transport protocol (RTP) packets, enabling reliable fax transmission over IP networks.
While the Hayes protocol was widely used in the past for modem communication, fax machines have their own specific protocols optimized for fax transmission.


From: jlemaire36 ***@***.***>
Sent: Sunday, July 9, 2023 4:40 AM
To: tolsen64/InternetModem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tolsen64/InternetModem] can you use it to emulate fax? (Issue #2)


i would like to know if it's possible to use it as a virtual fax modem so i could play around with fax softwares, that would be cool

**Comment by jlemaire36** [comment]
i was talking about fax SOFTWARES, which does use AT/Hayes command set when they come with Serial port support (eg: the windows copy and faxing utility)

**Comment by tolsen64** [comment]
Well then, just give it a try and see what happens. I built it a long time ago to get old computers like the Apple // able to dial in to BBS’s across the internet. I really don’t know anything about fax software or hardware.
